
services:
    db:
        image: postgres:16.3
        container_name: postgres_db
        environment:
            POSTGRES_DB: annotatex
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpassword
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - "5432:5432"

volumes:
    db_data: